movie_list/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('movies.urls'))
]

movies/urls.py
from django.urls import path
from .views import MovieList
from django.views.generic.base import RedirectView

urlpatterns = [
    path('movies', MovieList.as_view(), name='movies-list'),
    path('', RedirectView.as_view(url='movies', permanent=False), name='index')
]

movies/models.py
from django.db import models

# Create your models here.


class Movie(models.Model):
    """
    Movie model

    Contains all required movie info
    """
    movie_uid = models.CharField(max_length=255)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.movie_uid


class MovieCharacter(models.Model):
    """
    Movie character model
    """
    character_uid = models.CharField(max_length=255)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.character_uid

movies/views.py
from django.views.generic import ListView
from .models import Movie

from movies.tasks import gather_movie_data

# Create your views here.


class MovieList(ListView):
    """
    Main view to get list of Movie objects
    """
    model = Movie
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        # gather_movie_data()
        context['movie_list'] = Movie.objects.all()
        return context

movies/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
{#    <link rel="icon" href="../../../../favicon.ico">#}

    <title>Movie List</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.0/examples/album/album.css" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">About</h4>
                    <p class="text-muted">Ghibli Studio is a Japanese animation film studio based in Koganei,
                        Tokyo, Japan.[1] The studio is best known for its anime feature films, and
                        has also produced several short films, television commercials,
                        and one television film. It was founded on 15 June 1985, after the success of
                        Nausicaä of the Valley of the Wind (1984), with funding by Tokuma Shoten. </p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Contact</h4>
                    <ul class="list-unstyled">
                        <li><a href="#" class="text-white">Follow on Twitter</a></li>
                        <li><a href="#" class="text-white">Like on Facebook</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>Ghibli Movie List</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">Ghibli Movie Production</h1>
            <p class="lead text-muted">The Studio Ghibli API catalogs the people, places, and things found in the
                worlds of Ghibli. It was created to help users discover resources, consume them via HTTP requests,
                and interact with them in whatever way makes sense.</p>
{#            <p>#}
{#                <a href="#" class="btn btn-primary my-2">Main call to action</a>#}
{#                <a href="#" class="btn btn-secondary my-2">Secondary action</a>#}
{#            </p>#}
        </div>
    </section>


    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">

                {% block main %}

                {% endblock %}

            </div>
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting
            started guide</a>.</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script src="https://getbootstrap.com/docs/4.0/assets/js/vendor/holder.min.js"></script>
</body>
</html>

movies/templates/home.html
{% extends 'base.html' %}
{% block main %}

    {% for movie in movie_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&bg=55595c&fg=eceeef&text=Thumbnail"
                     alt="Card image cap">
                <div class="card-body">
                    <p class="card-text">{{ movie.name }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            {% if movie.moviecharacter_set.all %}
                                <button type="button" class="btn btn-sm btn-outline-secondary" data-toggle="modal"
                                        data-target="#exampleModal_{{ movie.id }}">Characters ({{ movie.moviecharacter_set.count }})
                                </button>
                            {% else %}
                                <button type="button" class="btn btn-sm btn-outline-secondary disabled">
                                    Characters ({{ movie.moviecharacter_set.count }})
                                </button>
                            {% endif %}
                        </div>
                    </div>
                    <div class="characters d-none">

                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="exampleModal_{{ movie.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Characters</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    {% if movie.moviecharacter_set.all %}
                        {% for character in movie.moviecharacter_set.all %}
                            <p>{{ character.name }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

{% endblock %}